# Generated by Django 5.2.4 on 2025-07-07 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mensaje_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='motivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='mensajes', to='api.motivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='mensajes', to='api.persona'),
            preserve_default=False,
        ),
    ]
